/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package animal;

import javax.swing.JOptionPane;

/**
 *
 * @author Angelica Guerrero
 */
public class Vclase1 extends javax.swing.JFrame {
    
    
    String filo,c;
    animalBR objbr = new animalBR();
    /**
     * Creates new form Vanimal
     */
    public Vclase1(String filo1) {
        initComponents();
        filo=filo1;
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cbx_glan = new javax.swing.JCheckBox();
        cbx_esqOs = new javax.swing.JCheckBox();
        cbx_esqCar = new javax.swing.JCheckBox();
        cbx_endo = new javax.swing.JCheckBox();
        cbx_pulm = new javax.swing.JCheckBox();
        cbx_bran = new javax.swing.JCheckBox();
        cbx_nata = new javax.swing.JCheckBox();
        cbx_boca = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();
        btn_encadenar = new javax.swing.JButton();
        btn_siguiente = new javax.swing.JButton();
        lbl_res = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        cbx_glan.setText("Glandulas mamarias");
        cbx_glan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbx_glanActionPerformed(evt);
            }
        });

        cbx_esqOs.setText("Esqueleto oseo");
        cbx_esqOs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbx_esqOsActionPerformed(evt);
            }
        });

        cbx_esqCar.setText("Esqueleto cartilaginoso");
        cbx_esqCar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbx_esqCarActionPerformed(evt);
            }
        });

        cbx_endo.setText("Endotormos");
        cbx_endo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbx_endoActionPerformed(evt);
            }
        });

        cbx_pulm.setText("Respiran mediante pulmones");
        cbx_pulm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbx_pulmActionPerformed(evt);
            }
        });

        cbx_bran.setText("Respiran mediante branqueas");
        cbx_bran.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbx_branActionPerformed(evt);
            }
        });

        cbx_nata.setText("Vejiga natatoria");
        cbx_nata.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbx_nataActionPerformed(evt);
            }
        });

        cbx_boca.setText("Boca sin mandibulas");
        cbx_boca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbx_bocaActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("Clase");

        btn_encadenar.setText("Encadenar");
        btn_encadenar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_encadenarActionPerformed(evt);
            }
        });

        btn_siguiente.setText("Siguiente");
        btn_siguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_siguienteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addComponent(btn_encadenar))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbx_glan)
                            .addComponent(cbx_esqOs)
                            .addComponent(cbx_esqCar)
                            .addComponent(cbx_endo)
                            .addComponent(cbx_bran)
                            .addComponent(cbx_pulm)
                            .addComponent(cbx_boca)
                            .addComponent(cbx_nata))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(btn_siguiente)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(lbl_res, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(41, 41, 41))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(jLabel1)
                        .addGap(13, 13, 13))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(cbx_glan)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbx_esqOs)
                    .addComponent(lbl_res, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbx_esqCar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbx_endo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbx_pulm)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbx_bran)
                .addGap(8, 8, 8)
                .addComponent(cbx_nata)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cbx_boca)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_encadenar)
                    .addComponent(btn_siguiente))
                .addContainerGap(49, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbx_glanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbx_glanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbx_glanActionPerformed

    private void cbx_esqOsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbx_esqOsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbx_esqOsActionPerformed

    private void cbx_esqCarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbx_esqCarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbx_esqCarActionPerformed

    private void cbx_endoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbx_endoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbx_endoActionPerformed

    private void cbx_pulmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbx_pulmActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbx_pulmActionPerformed

    private void cbx_branActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbx_branActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbx_branActionPerformed

    private void cbx_nataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbx_nataActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbx_nataActionPerformed

    private void cbx_bocaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbx_bocaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbx_bocaActionPerformed

    private void btn_encadenarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_encadenarActionPerformed
        // TODO add your handling code here:
        String glan = "", esqOs = "", esqCar = "", endo = "",pulm = "",bran = "",nata = "",boca = "";
        if (cbx_glan.isSelected()) {
            glan = "si";
        } else {
            glan = "no";
        }
        if (cbx_esqOs.isSelected()) {
            esqOs = "si";
        } else {
            esqOs = "no";
        }
        if (cbx_esqCar.isSelected()) {
            esqCar = "si";
        } else {
            esqCar = "no";
        }
        if (cbx_endo.isSelected()) {
            endo = "si";
        } else {
            endo = "no";
        }
        if (cbx_pulm.isSelected()) {
            pulm = "si";
        } else {
            pulm = "no";
        }
        if (cbx_bran.isSelected()) {
            bran = "si";
        } else {
            bran = "no";
        }
        if (cbx_nata.isSelected()) {
            nata = "si";
        } else {
            nata = "no";
        }
        if (cbx_boca.isSelected()) {
            boca = "si";
        } else {
            boca = "no";
        }
         System.out.println("\nGlandulas mamarias=" + glan + "\nEsqueleto oseo=" + esqOs + "\nEsqueleto cartilaginoso=" + esqCar + 
                 "\nEndotornmos="+endo+"\nRespiran mediante pulmones="+pulm+"\nRespiran mediante branqueas="+bran+"\nVejiga natatoria="+nata+"\nBoca sin mandibulas="+boca);
        c = objbr.getClase(filo,glan, esqOs, esqCar, endo,pulm,bran,nata,boca);
        System.out.println("Clase1=" + c);
        lbl_res.setText(c);
    }//GEN-LAST:event_btn_encadenarActionPerformed

    private void btn_siguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_siguienteActionPerformed
        // TODO add your handling code here:
        if (c == null) {
            JOptionPane.showMessageDialog(this,
                    "Verifica las entradas", "Error",
                    JOptionPane.ERROR_MESSAGE);
    }                                        
            if (c.equals("Amphibia")) {
                this.dispose();
            Vorden vorden = new Vorden(c);
            vorden.setVisible(true);
        }
        
    }//GEN-LAST:event_btn_siguienteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Vclase1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Vclase1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Vclase1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Vclase1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new Vclase1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_encadenar;
    private javax.swing.JButton btn_siguiente;
    private javax.swing.JCheckBox cbx_boca;
    private javax.swing.JCheckBox cbx_bran;
    private javax.swing.JCheckBox cbx_endo;
    private javax.swing.JCheckBox cbx_esqCar;
    private javax.swing.JCheckBox cbx_esqOs;
    private javax.swing.JCheckBox cbx_glan;
    private javax.swing.JCheckBox cbx_nata;
    private javax.swing.JCheckBox cbx_pulm;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lbl_res;
    // End of variables declaration//GEN-END:variables
}
