/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package animal;

import javax.swing.JOptionPane;

/**
 *
 * @author Angelica Guerrero
 */
public class Vespecie extends javax.swing.JFrame {
    
    
    String genero,c;
    animalBR objbr = new animalBR();
    /**
     * Creates new form Vanimal
     */
    public Vespecie(String genero1) {
        initComponents();
        genero=genero1;
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cbx_resp = new javax.swing.JCheckBox();
        cbx_manch = new javax.swing.JCheckBox();
        cbx_pata = new javax.swing.JCheckBox();
        cbx_verr = new javax.swing.JCheckBox();
        cbx_cuerp = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();
        btn_encadenar = new javax.swing.JButton();
        btn_siguiente = new javax.swing.JButton();
        lbl_res = new javax.swing.JLabel();
        cbx_color = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        cbx_resp.setText("Respiración branquial");
        cbx_resp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbx_respActionPerformed(evt);
            }
        });

        cbx_manch.setText("Patrón de manchas");
        cbx_manch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbx_manchActionPerformed(evt);
            }
        });

        cbx_pata.setText("Patas largas");
        cbx_pata.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbx_pataActionPerformed(evt);
            }
        });

        cbx_verr.setText("Piel con verrugas");
        cbx_verr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbx_verrActionPerformed(evt);
            }
        });

        cbx_cuerp.setText("Cuerpo robusto");
        cbx_cuerp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbx_cuerpActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("Especie");

        btn_encadenar.setText("Encadenar");
        btn_encadenar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_encadenarActionPerformed(evt);
            }
        });

        btn_siguiente.setText("Salir");
        btn_siguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_siguienteActionPerformed(evt);
            }
        });

        cbx_color.setText("Coloración en tonos marrones");
        cbx_color.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbx_colorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addComponent(btn_encadenar))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbx_resp)
                            .addComponent(cbx_manch)
                            .addComponent(cbx_pata)
                            .addComponent(cbx_verr)
                            .addComponent(cbx_cuerp)
                            .addComponent(cbx_color))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(btn_siguiente)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(lbl_res, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(41, 41, 41))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(jLabel1)
                        .addGap(13, 13, 13))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(cbx_resp)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbx_manch)
                    .addComponent(lbl_res, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbx_pata)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbx_verr)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbx_cuerp)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cbx_color)
                .addGap(72, 72, 72)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_encadenar)
                    .addComponent(btn_siguiente))
                .addContainerGap(49, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbx_respActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbx_respActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbx_respActionPerformed

    private void cbx_manchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbx_manchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbx_manchActionPerformed

    private void cbx_pataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbx_pataActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbx_pataActionPerformed

    private void cbx_verrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbx_verrActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbx_verrActionPerformed

    private void cbx_cuerpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbx_cuerpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbx_cuerpActionPerformed

    private void btn_encadenarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_encadenarActionPerformed
        // TODO add your handling code here:
        String resp = "", manch = "", pata = "", verr = "",cuerp = "",color = "";
        if (cbx_resp.isSelected()) {
            resp = "si";
        } else {
            resp = "no";
        }
        if (cbx_manch.isSelected()) {
            manch = "si";
        } else {
            manch = "no";
        }
        if (cbx_pata.isSelected()) {
            pata = "si";
        } else {
            pata = "no";
        }
        if (cbx_verr.isSelected()) {
            verr = "si";
        } else {
            verr = "no";
        }
        if (cbx_cuerp.isSelected()) {
            cuerp = "si";
        } else {
            cuerp = "no";
        }
        if (cbx_color.isSelected()) {
            color = "si";
        } else {
            color = "no";
        }
        
        
         System.out.println("\nRespiracion branquial=" + resp +"\nPatron de manchas=" + manch+ "\nPatas largas=" + pata + "\nPiel con verrugas=" + verr + 
                 "\nCuerpo robusto="+cuerp+"\nColoracion en tonos marrones="+color);
        c = objbr.getEspecie(genero, resp,manch, pata, verr, cuerp,color);
        System.out.println("Especie=" + c);
        lbl_res.setText(c);
    }//GEN-LAST:event_btn_encadenarActionPerformed

    private void btn_siguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_siguienteActionPerformed
        // TODO add your handling code here:
                                         
        if (c == null) {
            JOptionPane.showMessageDialog(this,
                    "Verifica las entradas", "Error",
                    JOptionPane.ERROR_MESSAGE);
    }
        if (c.equals("Tlaloci")) {
             JOptionPane.showMessageDialog(null, "Conclusion--->Rana tlaloc");
               System.exit(0);
        }
        
    }//GEN-LAST:event_btn_siguienteActionPerformed

    private void cbx_colorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbx_colorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbx_colorActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Vespecie.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Vespecie.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Vespecie.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Vespecie.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new Vclase1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_encadenar;
    private javax.swing.JButton btn_siguiente;
    private javax.swing.JCheckBox cbx_color;
    private javax.swing.JCheckBox cbx_cuerp;
    private javax.swing.JCheckBox cbx_manch;
    private javax.swing.JCheckBox cbx_pata;
    private javax.swing.JCheckBox cbx_resp;
    private javax.swing.JCheckBox cbx_verr;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lbl_res;
    // End of variables declaration//GEN-END:variables
}
