/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package animal;

import javax.swing.JOptionPane;

/**
 *
 * @author Angelica Guerrero
 */
public class VespecieAnei extends javax.swing.JFrame {
    
    
    String genero2,c;
    animalBR objbr = new animalBR();
    /**
     * Creates new form Vanimal
     */
    public VespecieAnei(String genero2) {
        initComponents();
        genero2=genero2;
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cbx_cab = new javax.swing.JCheckBox();
        cbx_ojo = new javax.swing.JCheckBox();
        cbx_dedo = new javax.swing.JCheckBox();
        cbx_color = new javax.swing.JCheckBox();
        cbx_crest = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();
        btn_encadenar = new javax.swing.JButton();
        btn_siguiente = new javax.swing.JButton();
        lbl_res = new javax.swing.JLabel();
        cbx_cola = new javax.swing.JCheckBox();
        cbx_manch = new javax.swing.JCheckBox();
        cbx_piel = new javax.swing.JCheckBox();
        cbx_patr = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        cbx_cab.setText("Cabeza ancha y plana");
        cbx_cab.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbx_cabActionPerformed(evt);
            }
        });

        cbx_ojo.setText("Ojos grandes");
        cbx_ojo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbx_ojoActionPerformed(evt);
            }
        });

        cbx_dedo.setText("Dedos largos");
        cbx_dedo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbx_dedoActionPerformed(evt);
            }
        });

        cbx_color.setText("Coloración uniforme");
        cbx_color.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbx_colorActionPerformed(evt);
            }
        });

        cbx_crest.setText("Presencia de crestas dorsales");
        cbx_crest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbx_crestActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("Especie");

        btn_encadenar.setText("Encadenar");
        btn_encadenar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_encadenarActionPerformed(evt);
            }
        });

        btn_siguiente.setText("Salir");
        btn_siguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_siguienteActionPerformed(evt);
            }
        });

        cbx_cola.setText("Cola muy larga ");
        cbx_cola.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbx_colaActionPerformed(evt);
            }
        });

        cbx_manch.setText("Manchas en la piel");
        cbx_manch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbx_manchActionPerformed(evt);
            }
        });

        cbx_piel.setText("Piel rugosa o granulada");
        cbx_piel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbx_pielActionPerformed(evt);
            }
        });

        cbx_patr.setText("Patrón de coloración ventral");
        cbx_patr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbx_patrActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addComponent(btn_encadenar))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbx_cab)
                            .addComponent(cbx_ojo)
                            .addComponent(cbx_dedo)
                            .addComponent(cbx_color)
                            .addComponent(cbx_crest)
                            .addComponent(cbx_cola)
                            .addComponent(cbx_manch)
                            .addComponent(cbx_piel)
                            .addComponent(cbx_patr))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(lbl_res, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(41, 41, 41))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btn_siguiente)
                        .addGap(66, 66, 66))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(jLabel1)
                        .addGap(13, 13, 13))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(cbx_cab)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbx_ojo)
                    .addComponent(lbl_res, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbx_dedo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbx_color)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbx_crest)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cbx_cola)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbx_manch)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbx_piel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(cbx_patr)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_encadenar)
                    .addComponent(btn_siguiente))
                .addGap(33, 33, 33))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbx_cabActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbx_cabActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbx_cabActionPerformed

    private void cbx_ojoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbx_ojoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbx_ojoActionPerformed

    private void cbx_dedoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbx_dedoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbx_dedoActionPerformed

    private void cbx_colorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbx_colorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbx_colorActionPerformed

    private void cbx_crestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbx_crestActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbx_crestActionPerformed

    private void btn_encadenarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_encadenarActionPerformed
        // TODO add your handling code here:
        String cab = "", ojo = "", dedo = "", color = "",crest = "",cola = "",manch = "",piel = "",patr = "";
        if (cbx_cab.isSelected()) {
            cab = "si";
        } else {
            cab = "no";
        }
        if (cbx_ojo.isSelected()) {
            ojo = "si";
        } else {
            ojo = "no";
        }
        if (cbx_dedo.isSelected()) {
            dedo = "si";
        } else {
            dedo = "no";
        }
        if (cbx_color.isSelected()) {
            color = "si";
        } else {
            color = "no";
        }
        if (cbx_crest.isSelected()) {
            crest = "si";
        } else {
            crest = "no";
        }
        if (cbx_cola.isSelected()) {
            cola = "si";
        } else {
            cola = "no";
        }
        if (cbx_manch.isSelected()) {
            manch = "si";
        } else {
            manch = "no";
        }
        if (cbx_piel.isSelected()) {
            piel = "si";
        } else {
            piel = "no";
        }
        if (cbx_patr.isSelected()) {
            patr = "si";
        } else {
            patr = "no";
        }
        
         System.out.println("\nCabeza Ancha y Plana=" + cab + "\nOjos Grandes=" + ojo + "\nDedos Largos=" + dedo + 
                   "\nColoración Uniforme=" + color + "\nPresencia de Crestas Dorsales=" + crest + 
                   "\nCola Muy Larga=" + cola + "\nManchas en la Piel=" + manch + 
                   "\nPiel Rugosa o Granulada=" + piel + "\nPatrón de Coloración Ventral=" + patr);
        c = objbr.getEspecieA(genero2, cab, ojo, dedo, color, crest, cola, manch, piel, patr);
        System.out.println("Especie=" + c);
        lbl_res.setText(c);
    }//GEN-LAST:event_btn_encadenarActionPerformed

    private void btn_siguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_siguienteActionPerformed
        // TODO add your handling code here:
                                         
        if (c == null) {
            JOptionPane.showMessageDialog(this,
                    "Verifica las entradas", "Error",
                    JOptionPane.ERROR_MESSAGE);
    }
        if (c.equals("Tlaloci")) {
             JOptionPane.showMessageDialog(null, "Conclusion--->Rana tlaloc");
               System.exit(0);
        }
        if (c.equals("A. lugubris")) {
             JOptionPane.showMessageDialog(null, "Conclusion--->Salamandra argoricola");
               System.exit(0);
        }
        
    }//GEN-LAST:event_btn_siguienteActionPerformed

    private void cbx_colaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbx_colaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbx_colaActionPerformed

    private void cbx_manchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbx_manchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbx_manchActionPerformed

    private void cbx_pielActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbx_pielActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbx_pielActionPerformed

    private void cbx_patrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbx_patrActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbx_patrActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VespecieAnei.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VespecieAnei.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VespecieAnei.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VespecieAnei.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new Vclase1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_encadenar;
    private javax.swing.JButton btn_siguiente;
    private javax.swing.JCheckBox cbx_cab;
    private javax.swing.JCheckBox cbx_cola;
    private javax.swing.JCheckBox cbx_color;
    private javax.swing.JCheckBox cbx_crest;
    private javax.swing.JCheckBox cbx_dedo;
    private javax.swing.JCheckBox cbx_manch;
    private javax.swing.JCheckBox cbx_ojo;
    private javax.swing.JCheckBox cbx_patr;
    private javax.swing.JCheckBox cbx_piel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lbl_res;
    // End of variables declaration//GEN-END:variables
}
