/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package animal;

import javax.swing.JOptionPane;

/**
 *
 * @author Angelica Guerrero
 */
public class Vfamilia extends javax.swing.JFrame {
    
    
    String orden,c;
    animalBR objbr = new animalBR();
    /**
     * Creates new form Vanimal
     */
    public Vfamilia(String orden1) {
        initComponents();
        orden=orden1;
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cbx_rug = new javax.swing.JCheckBox();
        cbx_lis = new javax.swing.JCheckBox();
        cbx_voc = new javax.swing.JCheckBox();
        cbx_hiber = new javax.swing.JCheckBox();
        cbx_ojo = new javax.swing.JCheckBox();
        cbx_agua = new javax.swing.JCheckBox();
        cbx_tierr = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();
        btn_encadenar = new javax.swing.JButton();
        btn_siguiente = new javax.swing.JButton();
        lbl_res = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        cbx_rug.setText("Piel rugosa");
        cbx_rug.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbx_rugActionPerformed(evt);
            }
        });

        cbx_lis.setText("Piel lisa");
        cbx_lis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbx_lisActionPerformed(evt);
            }
        });

        cbx_voc.setText("Vocalizaciones");
        cbx_voc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbx_vocActionPerformed(evt);
            }
        });

        cbx_hiber.setText("Hibernación");
        cbx_hiber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbx_hiberActionPerformed(evt);
            }
        });

        cbx_ojo.setText("Ojos grandes");
        cbx_ojo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbx_ojoActionPerformed(evt);
            }
        });

        cbx_agua.setText("Reproduccion en agua");
        cbx_agua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbx_aguaActionPerformed(evt);
            }
        });

        cbx_tierr.setText("Reproduccion en tierra");
        cbx_tierr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbx_tierrActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("Familia");

        btn_encadenar.setText("Encadenar");
        btn_encadenar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_encadenarActionPerformed(evt);
            }
        });

        btn_siguiente.setText("Siguiente");
        btn_siguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_siguienteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addComponent(btn_encadenar))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbx_rug)
                            .addComponent(cbx_lis)
                            .addComponent(cbx_voc)
                            .addComponent(cbx_hiber)
                            .addComponent(cbx_agua)
                            .addComponent(cbx_ojo)
                            .addComponent(cbx_tierr))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(btn_siguiente)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(lbl_res, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(41, 41, 41))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(jLabel1)
                        .addGap(13, 13, 13))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(cbx_rug)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbx_lis)
                    .addComponent(lbl_res, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbx_voc)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbx_hiber)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbx_ojo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbx_agua)
                .addGap(8, 8, 8)
                .addComponent(cbx_tierr)
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_encadenar)
                    .addComponent(btn_siguiente))
                .addContainerGap(49, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbx_rugActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbx_rugActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbx_rugActionPerformed

    private void cbx_lisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbx_lisActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbx_lisActionPerformed

    private void cbx_vocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbx_vocActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbx_vocActionPerformed

    private void cbx_hiberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbx_hiberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbx_hiberActionPerformed

    private void cbx_ojoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbx_ojoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbx_ojoActionPerformed

    private void cbx_aguaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbx_aguaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbx_aguaActionPerformed

    private void cbx_tierrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbx_tierrActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbx_tierrActionPerformed

    private void btn_encadenarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_encadenarActionPerformed
        // TODO add your handling code here:
        String rug = "", lis = "", voc = "", hiber = "",ojo = "",agua = "",tierr = "";
        if (cbx_rug.isSelected()) {
            rug = "si";
        } else {
            rug = "no";
        }
        if (cbx_lis.isSelected()) {
            lis = "si";
        } else {
            lis = "no";
        }
        if (cbx_voc.isSelected()) {
            voc = "si";
        } else {
            voc = "no";
        }
        if (cbx_hiber.isSelected()) {
            hiber = "si";
        } else {
            hiber = "no";
        }
        if (cbx_ojo.isSelected()) {
            ojo = "si";
        } else {
            ojo = "no";
        }
        if (cbx_agua.isSelected()) {
            agua = "si";
        } else {
            agua = "no";
        }
        if (cbx_tierr.isSelected()) {
            tierr = "si";
        } else {
            tierr = "no";
        }
        
         System.out.println("\nPiel rugosa=" + rug + "\nPiel lisa=" + lis + "\nVocalizaciones=" + voc + 
                 "\nHibernacion="+hiber+"\nOjos grandes="+ojo+"\nReproduccion en agua="+agua+"\nReproduccion en tierra="+tierr);
        c = objbr.getFamilia(orden, rug, lis, voc, hiber, ojo, agua, tierr);
        System.out.println("Familia3=" + c);
        lbl_res.setText(c);
    }//GEN-LAST:event_btn_encadenarActionPerformed

    private void btn_siguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_siguienteActionPerformed
        // TODO add your handling code here:
        if (c == null) {
            JOptionPane.showMessageDialog(this,
                    "Verifica las entradas", "Error",
                    JOptionPane.ERROR_MESSAGE);
    }                                        
            if (c.equals("Ranidae")) {
                this.dispose();
            Vgenero vgenero = new Vgenero(c);
            vgenero.setVisible(true);
        }
        
    }//GEN-LAST:event_btn_siguienteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Vfamilia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Vfamilia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Vfamilia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Vfamilia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new Vclase1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_encadenar;
    private javax.swing.JButton btn_siguiente;
    private javax.swing.JCheckBox cbx_agua;
    private javax.swing.JCheckBox cbx_hiber;
    private javax.swing.JCheckBox cbx_lis;
    private javax.swing.JCheckBox cbx_ojo;
    private javax.swing.JCheckBox cbx_rug;
    private javax.swing.JCheckBox cbx_tierr;
    private javax.swing.JCheckBox cbx_voc;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lbl_res;
    // End of variables declaration//GEN-END:variables
}
