/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package animal;

import javax.swing.JOptionPane;

/**
 *
 * @author Angelica Guerrero
 */
public class Vfamilia1 extends javax.swing.JFrame {
    
    
    String orden,c;
    animalBR objbr = new animalBR();
    /**
     * Creates new form Vanimal
     */
    public Vfamilia1(String orden1) {
        initComponents();
        orden=orden1;
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cbx_bran = new javax.swing.JCheckBox();
        cbx_pata = new javax.swing.JCheckBox();
        cbx_cuer = new javax.swing.JCheckBox();
        cbx_inter = new javax.swing.JCheckBox();
        cbx_exter = new javax.swing.JCheckBox();
        cbx_terr = new javax.swing.JCheckBox();
        cbx_acua = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();
        btn_encadenar = new javax.swing.JButton();
        btn_siguiente = new javax.swing.JButton();
        lbl_res = new javax.swing.JLabel();
        cbx_metam = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        cbx_bran.setText("Presencia de branquias en adultos");
        cbx_bran.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbx_branActionPerformed(evt);
            }
        });

        cbx_pata.setText("Patas bien desarrolladas");
        cbx_pata.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbx_pataActionPerformed(evt);
            }
        });

        cbx_cuer.setText("Cuerpo alargado");
        cbx_cuer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbx_cuerActionPerformed(evt);
            }
        });

        cbx_inter.setText("Fertilización interna");
        cbx_inter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbx_interActionPerformed(evt);
            }
        });

        cbx_exter.setText("Fertilización externa");
        cbx_exter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbx_exterActionPerformed(evt);
            }
        });

        cbx_terr.setText("Hábitat terrestre");
        cbx_terr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbx_terrActionPerformed(evt);
            }
        });

        cbx_acua.setText("Hábitat acuático");
        cbx_acua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbx_acuaActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("Familia");

        btn_encadenar.setText("Encadenar");
        btn_encadenar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_encadenarActionPerformed(evt);
            }
        });

        btn_siguiente.setText("Siguiente");
        btn_siguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_siguienteActionPerformed(evt);
            }
        });

        cbx_metam.setText("Metamorfosis completa");
        cbx_metam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbx_metamActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addComponent(btn_encadenar))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbx_bran)
                            .addComponent(cbx_pata)
                            .addComponent(cbx_cuer)
                            .addComponent(cbx_inter)
                            .addComponent(cbx_terr)
                            .addComponent(cbx_exter)
                            .addComponent(cbx_acua)
                            .addComponent(cbx_metam))))
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_res, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_siguiente)
                    .addComponent(jLabel1))
                .addGap(0, 9, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbx_bran)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_res, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbx_pata))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbx_cuer)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbx_inter)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbx_exter)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbx_terr)
                .addGap(8, 8, 8)
                .addComponent(cbx_acua)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbx_metam)
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_encadenar)
                    .addComponent(btn_siguiente))
                .addContainerGap(43, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbx_branActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbx_branActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbx_branActionPerformed

    private void cbx_pataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbx_pataActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbx_pataActionPerformed

    private void cbx_cuerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbx_cuerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbx_cuerActionPerformed

    private void cbx_interActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbx_interActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbx_interActionPerformed

    private void cbx_exterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbx_exterActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbx_exterActionPerformed

    private void cbx_terrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbx_terrActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbx_terrActionPerformed

    private void cbx_acuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbx_acuaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbx_acuaActionPerformed

    private void btn_encadenarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_encadenarActionPerformed
        // TODO add your handling code here:
        String bran = "", pata = "", cuer = "", inter = "",exter = "",terr = "",acua = "",metam = "";
        if (cbx_bran.isSelected()) {
            bran = "si";
        } else {
            bran = "no";
        }
        if (cbx_pata.isSelected()) {
            pata = "si";
        } else {
            pata = "no";
        }
        if (cbx_cuer.isSelected()) {
            cuer = "si";
        } else {
            cuer = "no";
        }
        if (cbx_inter.isSelected()) {
            inter = "si";
        } else {
            inter = "no";
        }
        if (cbx_exter.isSelected()) {
            exter = "si";
        } else {
            exter = "no";
        }
        if (cbx_terr.isSelected()) {
            terr = "si";
        } else {
            terr = "no";
        }
        if (cbx_acua.isSelected()) {
            acua = "si";
        } else {
            acua = "no";
        }
        if (cbx_metam.isSelected()) {
            metam = "si";
        } else {
            metam = "no";
        }
        
         System.out.println("\nPresencia de branquias en adultos=" + bran +
                   "\nPatas bien desarrolladas=" + pata +
                   "\nCuerpo alargado=" + cuer +
                   "\nFertilización interna=" + inter +
                   "\nFertilización externa=" + exter +
                   "\nHábitat terrestre=" + terr +
                   "\nHábitat acuático=" + acua +
                   "\nMetamorfosis completa=" + metam);
        c = objbr.getFamilia2(orden, bran, pata, cuer, inter, exter, terr, acua, metam);
         System.out.println("Familia1=" + c);
        lbl_res.setText(c);
    }//GEN-LAST:event_btn_encadenarActionPerformed

    private void btn_siguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_siguienteActionPerformed
        // TODO add your handling code here:
        if (c == null) {
            JOptionPane.showMessageDialog(this,
                    "Verifica las entradas", "Error",
                    JOptionPane.ERROR_MESSAGE);
    }                                        
            if (c.equals("Ranidae")) {
                this.dispose();
            Vgenero vgenero = new Vgenero(c);
            vgenero.setVisible(true);
        }
            if (c.equals("Ambystomatidae")) {
                this.dispose();
            VgeneroAmbyst vgenero2 = new VgeneroAmbyst(c);
            vgenero2.setVisible(true);
        }
            if (c.equals("Plethodontidae")) {
                this.dispose();
            VgeneroPlent vgenero3 = new VgeneroPlent(c);
            vgenero3.setVisible(true);
        }
        
    }//GEN-LAST:event_btn_siguienteActionPerformed

    private void cbx_metamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbx_metamActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbx_metamActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Vfamilia1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Vfamilia1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Vfamilia1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Vfamilia1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new Vclase1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_encadenar;
    private javax.swing.JButton btn_siguiente;
    private javax.swing.JCheckBox cbx_acua;
    private javax.swing.JCheckBox cbx_bran;
    private javax.swing.JCheckBox cbx_cuer;
    private javax.swing.JCheckBox cbx_exter;
    private javax.swing.JCheckBox cbx_inter;
    private javax.swing.JCheckBox cbx_metam;
    private javax.swing.JCheckBox cbx_pata;
    private javax.swing.JCheckBox cbx_terr;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lbl_res;
    // End of variables declaration//GEN-END:variables
}
