/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package animal;

import javax.swing.JOptionPane;

/**
 *
 * @author Angelica Guerrero
 */
public class Vfilo1 extends javax.swing.JFrame {
    
    String reino,c;
    animalBR objbr = new animalBR();
    /**
     * Creates new form Vanimal
     */
    public Vfilo1(String reino1) {
         reino=reino1;
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cbx_sim = new javax.swing.JCheckBox();
        cbx_seg = new javax.swing.JCheckBox();
        cbx_esq = new javax.swing.JCheckBox();
        cbx_cav = new javax.swing.JCheckBox();
        cbx_sist = new javax.swing.JCheckBox();
        cbx_ap = new javax.swing.JCheckBox();
        cbx_asex = new javax.swing.JCheckBox();
        cbx_sex = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();
        btn_encadenar = new javax.swing.JButton();
        btn_siguiente = new javax.swing.JButton();
        lbl_res = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        cbx_sim.setText("Simetria bilateral");
        cbx_sim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbx_simActionPerformed(evt);
            }
        });

        cbx_seg.setText("Segmentación");
        cbx_seg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbx_segActionPerformed(evt);
            }
        });

        cbx_esq.setText("Esqueleto");
        cbx_esq.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbx_esqActionPerformed(evt);
            }
        });

        cbx_cav.setText("Cavidad corporal");
        cbx_cav.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbx_cavActionPerformed(evt);
            }
        });

        cbx_sist.setText("Sistema digestivo");
        cbx_sist.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbx_sistActionPerformed(evt);
            }
        });

        cbx_ap.setText("Apendices articulados");
        cbx_ap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbx_apActionPerformed(evt);
            }
        });

        cbx_asex.setText("Reproduccion asexual");
        cbx_asex.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbx_asexActionPerformed(evt);
            }
        });

        cbx_sex.setText("Reproduccion sexual");
        cbx_sex.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbx_sexActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("Filo");

        btn_encadenar.setText("Encadenar");
        btn_encadenar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_encadenarActionPerformed(evt);
            }
        });

        btn_siguiente.setText("Siguiente");
        btn_siguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_siguienteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addComponent(btn_encadenar))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbx_sim)
                            .addComponent(cbx_seg)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(cbx_esq)
                                .addComponent(cbx_cav)
                                .addComponent(cbx_ap)
                                .addComponent(cbx_sist)
                                .addComponent(cbx_asex, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(cbx_sex)))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(btn_siguiente)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(lbl_res, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(22, 22, 22))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(jLabel1))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(cbx_sim)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_res, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbx_seg))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(cbx_esq)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbx_cav)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbx_sist)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbx_ap)
                        .addGap(28, 28, 28))
                    .addComponent(cbx_asex, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cbx_sex)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_encadenar)
                    .addComponent(btn_siguiente))
                .addContainerGap(50, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbx_simActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbx_simActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbx_simActionPerformed

    private void cbx_segActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbx_segActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbx_segActionPerformed

    private void cbx_esqActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbx_esqActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbx_esqActionPerformed

    private void cbx_cavActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbx_cavActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbx_cavActionPerformed

    private void cbx_sistActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbx_sistActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbx_sistActionPerformed

    private void cbx_apActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbx_apActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbx_apActionPerformed

    private void cbx_asexActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbx_asexActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbx_asexActionPerformed

    private void cbx_sexActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbx_sexActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbx_sexActionPerformed

    private void btn_encadenarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_encadenarActionPerformed
        // TODO add your handling code here:
        String sim = "", seg = "", esq = "", cav = "",sist = "",ap = "",asex = "",sex = "";
        if (cbx_sim.isSelected()) {
            sim = "si";
        } else {
            sim = "no";
        }
        if (cbx_seg.isSelected()) {
            seg = "si";
        } else {
            seg = "no";
        }
        if (cbx_esq.isSelected()) {
            esq = "si";
        } else {
            esq = "no";
        }
        if (cbx_cav.isSelected()) {
            cav = "si";
        } else {
            cav = "no";
        }
        if (cbx_sist.isSelected()) {
            sist = "si";
        } else {
            sist = "no";
        }
        if (cbx_ap.isSelected()) {
            ap = "si";
        } else {
            ap = "no";
        }
        if (cbx_asex.isSelected()) {
            asex = "si";
        } else {
            asex = "no";
        }
        if (cbx_sex.isSelected()) {
            sex = "si";
        } else {
            sex = "no";
        }
         System.out.println("\nSimetria bilateral=" + sim + "\nSegmentacion=" + seg + "\nEsqueleto=" + esq + "\nCavidad corporal=" + cav+
                 "\nSistema digestivo="+sist+"\nApendices articulados="+ap+"\nReproduccion asexual="+asex+"\nReproduccion sexual="+sex);
        c = objbr.getFilo(reino,sim, seg, esq, cav,sist,ap,asex,sex);
        System.out.println("Filo1=" + c);
        lbl_res.setText(c);
    }//GEN-LAST:event_btn_encadenarActionPerformed

    private void btn_siguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_siguienteActionPerformed
        // TODO add your handling code here:
        if (c == null) {
            JOptionPane.showMessageDialog(this,
                    "Verifica las entradas", "Error",
                    JOptionPane.ERROR_MESSAGE);
    }                                        
            if (c.equals("Chordata") ) {
                this.dispose();
            Vclase1 clase1 = new Vclase1(c);
            clase1.setVisible(true);
        }
    }//GEN-LAST:event_btn_siguienteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Vfilo1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Vfilo1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Vfilo1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Vfilo1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
               // new Vfilo1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_encadenar;
    private javax.swing.JButton btn_siguiente;
    private javax.swing.JCheckBox cbx_ap;
    private javax.swing.JCheckBox cbx_asex;
    private javax.swing.JCheckBox cbx_cav;
    private javax.swing.JCheckBox cbx_esq;
    private javax.swing.JCheckBox cbx_seg;
    private javax.swing.JCheckBox cbx_sex;
    private javax.swing.JCheckBox cbx_sim;
    private javax.swing.JCheckBox cbx_sist;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lbl_res;
    // End of variables declaration//GEN-END:variables
}
