/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package animal;

import javax.swing.JOptionPane;

/**
 *
 * @author Angelica Guerrero
 */
public class VgeneroAmbyst extends javax.swing.JFrame {
    
    
    String familia2,c;
    animalBR objbr = new animalBR();
    /**
     * Creates new form Vanimal
     */
    public VgeneroAmbyst(String familia2) {
        initComponents();
        this.setLocationRelativeTo(null);
        familia2=familia2;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cbx_col = new javax.swing.JCheckBox();
        cbx_habit = new javax.swing.JCheckBox();
        cbx_bran = new javax.swing.JCheckBox();
        cbx_neote = new javax.swing.JCheckBox();
        cbx_inter = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();
        btn_encadenar = new javax.swing.JButton();
        btn_siguiente = new javax.swing.JButton();
        lbl_res = new javax.swing.JLabel();
        cbx_exter = new javax.swing.JCheckBox();
        cbx_metam = new javax.swing.JCheckBox();
        cbx_neo = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        cbx_col.setText("Coloracion con manchas");
        cbx_col.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbx_colActionPerformed(evt);
            }
        });

        cbx_habit.setText("Habitat en arrollos de montaña");
        cbx_habit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbx_habitActionPerformed(evt);
            }
        });

        cbx_bran.setText("Branquias en adultos");
        cbx_bran.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbx_branActionPerformed(evt);
            }
        });

        cbx_neote.setText("Estado neotenico frecuente");
        cbx_neote.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbx_neoteActionPerformed(evt);
            }
        });

        cbx_inter.setText("Fertilizacion interna");
        cbx_inter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbx_interActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("Genero");

        btn_encadenar.setText("Encadenar");
        btn_encadenar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_encadenarActionPerformed(evt);
            }
        });

        btn_siguiente.setText("Siguiente");
        btn_siguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_siguienteActionPerformed(evt);
            }
        });

        cbx_exter.setText("Fertilizacion externa");
        cbx_exter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbx_exterActionPerformed(evt);
            }
        });

        cbx_metam.setText("Metamorfosis completa");
        cbx_metam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbx_metamActionPerformed(evt);
            }
        });

        cbx_neo.setText("Neotenia frecuente");
        cbx_neo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbx_neoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addComponent(btn_encadenar))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbx_col)
                            .addComponent(cbx_habit)
                            .addComponent(cbx_bran)
                            .addComponent(cbx_neote)
                            .addComponent(cbx_inter)
                            .addComponent(cbx_exter)
                            .addComponent(cbx_metam)
                            .addComponent(cbx_neo))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(btn_siguiente)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(lbl_res, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(41, 41, 41))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(jLabel1)
                        .addGap(13, 13, 13))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(cbx_col)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbx_habit)
                    .addComponent(lbl_res, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbx_bran)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbx_neote)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbx_inter)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbx_exter)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbx_metam)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbx_neo)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_encadenar)
                    .addComponent(btn_siguiente))
                .addContainerGap(49, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbx_colActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbx_colActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbx_colActionPerformed

    private void cbx_habitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbx_habitActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbx_habitActionPerformed

    private void cbx_branActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbx_branActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbx_branActionPerformed

    private void cbx_neoteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbx_neoteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbx_neoteActionPerformed

    private void cbx_interActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbx_interActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbx_interActionPerformed

    private void btn_encadenarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_encadenarActionPerformed
        // TODO add your handling code here:
        String col = "", habit = "", bran = "", neote = "",inter = "",exter = "",metam = "",neo = "";
        if (cbx_col.isSelected()) {
            col = "si";
        } else {
            col = "no";
        }
        if (cbx_habit.isSelected()) {
            habit = "si";
        } else {
            habit = "no";
        }
        if (cbx_bran.isSelected()) {
            bran = "si";
        } else {
            bran = "no";
        }
        if (cbx_neote.isSelected()) {
            neote = "si";
        } else {
            neote = "no";
        }
        if (cbx_inter.isSelected()) {
            inter = "si";
        } else {
            inter = "no";
        }
        if (cbx_exter.isSelected()) {
            exter = "si";
        } else {
            exter = "no";
        }
        if (cbx_metam.isSelected()) {
            metam = "si";
        } else {
            metam = "no";
        }
        if (cbx_neo.isSelected()) {
            neo = "si";
        } else {
            neo = "no";
        }
        
        
        
         System.out.println("\nColoración con manchas=" + col + 
                   "\nHábitat en arroyos de montaña=" + habit + 
                   "\nBranquias en adultos=" + bran + 
                   "\nEstado neotenico frecuente=" + neote + 
                   "\nFertilizacion interna=" + inter + 
                   "\nFertilizacion externa=" + exter + 
                   "\nMetamorfosis completa=" + metam + 
                   "\nNeotenia frecuente=" + neo);
        c = objbr.getGenero2(familia2, col, habit, bran, neote, inter, exter, metam, neo);
        System.out.println("Genero1=" + c);
        lbl_res.setText(c);
    }//GEN-LAST:event_btn_encadenarActionPerformed

    private void btn_siguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_siguienteActionPerformed
        // TODO add your handling code here:
        if (c == null) {
            JOptionPane.showMessageDialog(this,
                    "Verifica las entradas", "Error",
                    JOptionPane.ERROR_MESSAGE);
    }                                        
            if (c.equals("Lithobates")) {
                this.dispose();
            Vespecie vespecie = new Vespecie(c);
            vespecie.setVisible(true);
        }
            if (c.equals("Ambystoma")) {
                this.dispose();
            VespecieAmby vespecie = new VespecieAmby(c);
            vespecie.setVisible(true);
        }
        
    }//GEN-LAST:event_btn_siguienteActionPerformed

    private void cbx_exterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbx_exterActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbx_exterActionPerformed

    private void cbx_metamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbx_metamActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbx_metamActionPerformed

    private void cbx_neoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbx_neoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbx_neoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VgeneroAmbyst.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VgeneroAmbyst.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VgeneroAmbyst.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VgeneroAmbyst.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new Vclase1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_encadenar;
    private javax.swing.JButton btn_siguiente;
    private javax.swing.JCheckBox cbx_bran;
    private javax.swing.JCheckBox cbx_col;
    private javax.swing.JCheckBox cbx_exter;
    private javax.swing.JCheckBox cbx_habit;
    private javax.swing.JCheckBox cbx_inter;
    private javax.swing.JCheckBox cbx_metam;
    private javax.swing.JCheckBox cbx_neo;
    private javax.swing.JCheckBox cbx_neote;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lbl_res;
    // End of variables declaration//GEN-END:variables
}
