/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package animal;

import javax.swing.JOptionPane;

/**
 *
 * @author Angelica Guerrero
 */
public class Vgenero extends javax.swing.JFrame {
    
    
    String familia,c;
    animalBR objbr = new animalBR();
    /**
     * Creates new form Vanimal
     */
    public Vgenero(String familia1) {
        initComponents();
        this.setLocationRelativeTo(null);
        familia=familia1;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cbx_trop = new javax.swing.JCheckBox();
        cbx_acua = new javax.swing.JCheckBox();
        cbx_depr = new javax.swing.JCheckBox();
        cbx_piel = new javax.swing.JCheckBox();
        cbx_espe = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();
        btn_encadenar = new javax.swing.JButton();
        btn_siguiente = new javax.swing.JButton();
        lbl_res = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        cbx_trop.setText("Habitat tropical");
        cbx_trop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbx_tropActionPerformed(evt);
            }
        });

        cbx_acua.setText("Habitat acuatico");
        cbx_acua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbx_acuaActionPerformed(evt);
            }
        });

        cbx_depr.setText("Depredadores naturales");
        cbx_depr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbx_deprActionPerformed(evt);
            }
        });

        cbx_piel.setText("Piel glandular venenosa");
        cbx_piel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbx_pielActionPerformed(evt);
            }
        });

        cbx_espe.setText("Especies terrestres");
        cbx_espe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbx_espeActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("Genero");

        btn_encadenar.setText("Encadenar");
        btn_encadenar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_encadenarActionPerformed(evt);
            }
        });

        btn_siguiente.setText("Siguiente");
        btn_siguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_siguienteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addComponent(btn_encadenar))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbx_trop)
                            .addComponent(cbx_acua)
                            .addComponent(cbx_depr)
                            .addComponent(cbx_piel)
                            .addComponent(cbx_espe))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(btn_siguiente)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(lbl_res, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(41, 41, 41))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(jLabel1)
                        .addGap(13, 13, 13))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(cbx_trop)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbx_acua)
                    .addComponent(lbl_res, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbx_depr)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbx_piel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbx_espe)
                .addGap(104, 104, 104)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_encadenar)
                    .addComponent(btn_siguiente))
                .addContainerGap(49, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbx_tropActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbx_tropActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbx_tropActionPerformed

    private void cbx_acuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbx_acuaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbx_acuaActionPerformed

    private void cbx_deprActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbx_deprActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbx_deprActionPerformed

    private void cbx_pielActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbx_pielActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbx_pielActionPerformed

    private void cbx_espeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbx_espeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbx_espeActionPerformed

    private void btn_encadenarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_encadenarActionPerformed
        // TODO add your handling code here:
        String trop = "", lis = "", acua = "", depr = "",piel = "",espe = "";
        if (cbx_trop.isSelected()) {
            trop = "si";
        } else {
            trop = "no";
        }
        if (cbx_acua.isSelected()) {
            acua = "si";
        } else {
            acua = "no";
        }
        if (cbx_depr.isSelected()) {
            depr = "si";
        } else {
            depr = "no";
        }
        if (cbx_piel.isSelected()) {
            piel = "si";
        } else {
            piel = "no";
        }
        if (cbx_espe.isSelected()) {
            espe = "si";
        } else {
            espe = "no";
        }
        
        
         System.out.println("\nHabitat tropical=" + trop +"\nHabitat acuatico=" + acua+ "\nDepredadores naturales=" + depr + "\nPiel glandular venenosa=" + piel + 
                 "\nEspecies terrestres="+espe);
        c = objbr.getGenero(familia, trop,depr, acua, piel, espe);
        System.out.println("Genero1=" + c);
        lbl_res.setText(c);
    }//GEN-LAST:event_btn_encadenarActionPerformed

    private void btn_siguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_siguienteActionPerformed
        // TODO add your handling code here:
        if (c == null) {
            JOptionPane.showMessageDialog(this,
                    "Verifica las entradas", "Error",
                    JOptionPane.ERROR_MESSAGE);
    }                                        
            if (c.equals("Lithobates")) {
                this.dispose();
            Vespecie vespecie = new Vespecie(c);
            vespecie.setVisible(true);
        }
        
    }//GEN-LAST:event_btn_siguienteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Vgenero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Vgenero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Vgenero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Vgenero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new Vclase1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_encadenar;
    private javax.swing.JButton btn_siguiente;
    private javax.swing.JCheckBox cbx_acua;
    private javax.swing.JCheckBox cbx_depr;
    private javax.swing.JCheckBox cbx_espe;
    private javax.swing.JCheckBox cbx_piel;
    private javax.swing.JCheckBox cbx_trop;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lbl_res;
    // End of variables declaration//GEN-END:variables
}
