/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package animal;

import javax.swing.JOptionPane;

/**
 *
 * @author Angelica Guerrero
 */
public class VgeneroPlent extends javax.swing.JFrame {
    
    
    String familia2,c;
    animalBR objbr = new animalBR();
    /**
     * Creates new form Vanimal
     */
    public VgeneroPlent(String familia2) {
        initComponents();
        this.setLocationRelativeTo(null);
        familia2=familia2;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cbx_col = new javax.swing.JCheckBox();
        cbx_bran = new javax.swing.JCheckBox();
        cbx_terr = new javax.swing.JCheckBox();
        cbx_inter = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();
        btn_encadenar = new javax.swing.JButton();
        btn_siguiente = new javax.swing.JButton();
        lbl_res = new javax.swing.JLabel();
        cbx_habter = new javax.swing.JCheckBox();
        cbx_acua = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        cbx_col.setText("Coloracion brillante o variada");
        cbx_col.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbx_colActionPerformed(evt);
            }
        });

        cbx_bran.setText("Branquias en adultos");
        cbx_bran.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbx_branActionPerformed(evt);
            }
        });

        cbx_terr.setText("Reproduccion terrestre");
        cbx_terr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbx_terrActionPerformed(evt);
            }
        });

        cbx_inter.setText("Fertilizacion interna");
        cbx_inter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbx_interActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("Genero");

        btn_encadenar.setText("Encadenar");
        btn_encadenar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_encadenarActionPerformed(evt);
            }
        });

        btn_siguiente.setText("Siguiente");
        btn_siguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_siguienteActionPerformed(evt);
            }
        });

        cbx_habter.setText("Habitat terrestre");
        cbx_habter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbx_habterActionPerformed(evt);
            }
        });

        cbx_acua.setText("Habitat acuatico");
        cbx_acua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbx_acuaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbx_bran)
                            .addComponent(cbx_terr)
                            .addComponent(cbx_inter)
                            .addComponent(cbx_habter)
                            .addComponent(cbx_acua)
                            .addComponent(cbx_col))
                        .addGap(46, 46, 46)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_res, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(btn_encadenar)
                        .addGap(35, 35, 35)
                        .addComponent(btn_siguiente)))
                .addGap(0, 10, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbx_bran)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_res, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbx_inter))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cbx_terr)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cbx_habter)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbx_acua)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cbx_col)
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_encadenar)
                    .addComponent(btn_siguiente))
                .addContainerGap(63, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbx_colActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbx_colActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbx_colActionPerformed

    private void cbx_branActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbx_branActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbx_branActionPerformed

    private void cbx_terrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbx_terrActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbx_terrActionPerformed

    private void cbx_interActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbx_interActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbx_interActionPerformed

    private void btn_encadenarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_encadenarActionPerformed
        // TODO add your handling code here:
        String col = "", habter = "", bran = "", acua = "",terr = "",inter = "";
        if (cbx_col.isSelected()) {
            col = "si";
        } else {
            col = "no";
        }
        
        if (cbx_bran.isSelected()) {
            bran = "si";
        } else {
            bran = "no";
        }
        if (cbx_terr.isSelected()) {
            terr = "si";
        } else {
            terr = "no";
        }
        if (cbx_inter.isSelected()) {
            inter = "si";
        } else {
            inter = "no";
        }
        if (cbx_habter.isSelected()) {
            habter = "si";
        } else {
            habter = "no";
        }
        if (cbx_acua.isSelected()) {
            acua = "si";
        } else {
            acua = "no";
        }
        
        
        
        
         System.out.println("\nBranquias en Adultos=" + bran + 
                   "\nFertilizacion Interna=" + inter + 
                   "\nReproduccion Terrestre=" + terr + 
                   "\nHabitat Terrestre=" + habter + 
                   "\nHabitat Acuatico=" + acua + 
                   "\nColoracion brillante o variada.=" + col);
        c = objbr.getGeneroP(familia2, bran, inter, terr, habter, acua, col);
        System.out.println("Genero2=" + c);
        lbl_res.setText(c);
    }//GEN-LAST:event_btn_encadenarActionPerformed

    private void btn_siguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_siguienteActionPerformed
        // TODO add your handling code here:
        if (c == null) {
            JOptionPane.showMessageDialog(this,
                    "Verifica las entradas", "Error",
                    JOptionPane.ERROR_MESSAGE);
    }                                        
            if (c.equals("Pseudoeurycea")) {
                this.dispose();
            VespeciePseud vespecie = new VespeciePseud(c);
            vespecie.setVisible(true);
        }
            if (c.equals("Aneides")) {
                this.dispose();
            VespecieAnei vespecie = new VespecieAnei(c);
            vespecie.setVisible(true);
        }
        
    }//GEN-LAST:event_btn_siguienteActionPerformed

    private void cbx_habterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbx_habterActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbx_habterActionPerformed

    private void cbx_acuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbx_acuaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbx_acuaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VgeneroPlent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VgeneroPlent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VgeneroPlent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VgeneroPlent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new Vclase1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_encadenar;
    private javax.swing.JButton btn_siguiente;
    private javax.swing.JCheckBox cbx_acua;
    private javax.swing.JCheckBox cbx_bran;
    private javax.swing.JCheckBox cbx_col;
    private javax.swing.JCheckBox cbx_habter;
    private javax.swing.JCheckBox cbx_inter;
    private javax.swing.JCheckBox cbx_terr;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lbl_res;
    // End of variables declaration//GEN-END:variables
}
