/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package animal;

import javax.swing.JOptionPane;

/**
 *
 * @author Angelica Guerrero
 */
public class Vorden extends javax.swing.JFrame {
    
    String clase,c;
    animalBR objbr = new animalBR();
    /**
     * Creates new form Vanimal
     */
    public Vorden(String clase1) {
         clase=clase1;
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cbx_pres = new javax.swing.JCheckBox();
        cbx_patas = new javax.swing.JCheckBox();
        cbx_cuerp = new javax.swing.JCheckBox();
        cbx_inte = new javax.swing.JCheckBox();
        cbx_ext = new javax.swing.JCheckBox();
        cbx_resp = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();
        btn_encadenar = new javax.swing.JButton();
        btn_siguiente = new javax.swing.JButton();
        lbl_res = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        cbx_pres.setText("Presencia de cola");
        cbx_pres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbx_presActionPerformed(evt);
            }
        });

        cbx_patas.setText("Patas bien desarrolladas");
        cbx_patas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbx_patasActionPerformed(evt);
            }
        });

        cbx_cuerp.setText("Cuerpo alargado");
        cbx_cuerp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbx_cuerpActionPerformed(evt);
            }
        });

        cbx_inte.setText("Fertilizacion interna");
        cbx_inte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbx_inteActionPerformed(evt);
            }
        });

        cbx_ext.setText("Fertilizacion externa");
        cbx_ext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbx_extActionPerformed(evt);
            }
        });

        cbx_resp.setText("Respiracion cutanea");
        cbx_resp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbx_respActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("Orden");

        btn_encadenar.setText("Encadenar");
        btn_encadenar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_encadenarActionPerformed(evt);
            }
        });

        btn_siguiente.setText("Siguiente");
        btn_siguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_siguienteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addComponent(btn_encadenar))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbx_pres)
                            .addComponent(cbx_patas)
                            .addComponent(cbx_cuerp)
                            .addComponent(cbx_inte)
                            .addComponent(cbx_resp)
                            .addComponent(cbx_ext))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(btn_siguiente)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(lbl_res, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(22, 22, 22))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(jLabel1))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(cbx_pres)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_res, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbx_patas))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbx_cuerp)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbx_inte)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbx_ext)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbx_resp)
                .addGap(78, 78, 78)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_encadenar)
                    .addComponent(btn_siguiente))
                .addContainerGap(50, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbx_presActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbx_presActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbx_presActionPerformed

    private void cbx_patasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbx_patasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbx_patasActionPerformed

    private void cbx_cuerpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbx_cuerpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbx_cuerpActionPerformed

    private void cbx_inteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbx_inteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbx_inteActionPerformed

    private void cbx_extActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbx_extActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbx_extActionPerformed

    private void cbx_respActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbx_respActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbx_respActionPerformed

    private void btn_encadenarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_encadenarActionPerformed
        // TODO add your handling code here:
        String pres = "", pata = "", cuerp = "", inter = "",exter = "",resp = "";
        if (cbx_pres.isSelected()) {
            pres = "si";
        } else {
            pres = "no";
        }
        if (cbx_patas.isSelected()) {
            pata = "si";
        } else {
            pata = "no";
        }
        if (cbx_cuerp.isSelected()) {
            cuerp = "si";
        } else {
            cuerp = "no";
        }
        if (cbx_inte.isSelected()) {
            inter = "si";
        } else {
            inter = "no";
        }
        if (cbx_ext.isSelected()) {
            exter = "si";
        } else {
            exter = "no";
        }
        if (cbx_resp.isSelected()) {
            resp = "si";
        } else {
            resp = "no";
        }
        
         System.out.println("\nPresencia de cola=" + pres + "\nPatas bien desarrolladas=" + pata + "\nCuerpo alargado=" + cuerp + "\nFertilizacion interna=" + inter+
                 "\nFertilizacion externa="+exter+"\nRespiracion cutanea="+resp);
        c = objbr.getOrden(clase,pres, pata, cuerp, inter,exter,resp);
        System.out.println("Orden1=" + c);
        lbl_res.setText(c);
    }//GEN-LAST:event_btn_encadenarActionPerformed

    private void btn_siguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_siguienteActionPerformed
        // TODO add your handling code here:
        if (c == null) {
            JOptionPane.showMessageDialog(this,
                    "Verifica las entradas", "Error",
                    JOptionPane.ERROR_MESSAGE);
    }                                        
            if (c.equals("Anura") ) {
                this.dispose();
            Vfamilia vfamilia = new Vfamilia(c);
            vfamilia.setVisible(true);
        }
            if (c.equals("Caudata") ) {
                this.dispose();
            Vfamilia1 vfamilia1 = new Vfamilia1(c);
            vfamilia1.setVisible(true);
        }
            
    }//GEN-LAST:event_btn_siguienteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Vorden.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Vorden.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Vorden.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Vorden.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
               // new Vfilo1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_encadenar;
    private javax.swing.JButton btn_siguiente;
    private javax.swing.JCheckBox cbx_cuerp;
    private javax.swing.JCheckBox cbx_ext;
    private javax.swing.JCheckBox cbx_inte;
    private javax.swing.JCheckBox cbx_patas;
    private javax.swing.JCheckBox cbx_pres;
    private javax.swing.JCheckBox cbx_resp;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lbl_res;
    // End of variables declaration//GEN-END:variables
}
