/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package animal;

import javax.swing.JOptionPane;

/**
 *
 * @author Angelica Guerrero
 */
public class Vreino extends javax.swing.JFrame {
    
    String c;
    animalBR objbr = new animalBR();
    /**
     * Creates new form Vanimal
     */
    public Vreino() {
        initComponents();
        this.setLocationRelativeTo(null); 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cbx_eucariotas = new javax.swing.JCheckBox();
        cbx_procariotas = new javax.swing.JCheckBox();
        cbx_unicelular = new javax.swing.JCheckBox();
        cbx_multicelular = new javax.swing.JCheckBox();
        cbx_autotrofo = new javax.swing.JCheckBox();
        cbx_heterotrofo = new javax.swing.JCheckBox();
        cbx_paredCelular = new javax.swing.JCheckBox();
        cbx_movillidad = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();
        btn_encadenar = new javax.swing.JButton();
        btn_siguiente = new javax.swing.JButton();
        lbl_res = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        cbx_eucariotas.setText("Eucariotas");
        cbx_eucariotas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbx_eucariotasActionPerformed(evt);
            }
        });

        cbx_procariotas.setText("Procariotas");
        cbx_procariotas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbx_procariotasActionPerformed(evt);
            }
        });

        cbx_unicelular.setText("Uniceluar");
        cbx_unicelular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbx_unicelularActionPerformed(evt);
            }
        });

        cbx_multicelular.setText("Multicelular");
        cbx_multicelular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbx_multicelularActionPerformed(evt);
            }
        });

        cbx_autotrofo.setText("Autotrofo");
        cbx_autotrofo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbx_autotrofoActionPerformed(evt);
            }
        });

        cbx_heterotrofo.setText("Heterotrofo");
        cbx_heterotrofo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbx_heterotrofoActionPerformed(evt);
            }
        });

        cbx_paredCelular.setText("Pared celular");
        cbx_paredCelular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbx_paredCelularActionPerformed(evt);
            }
        });

        cbx_movillidad.setText("Movilidad");
        cbx_movillidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbx_movillidadActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("Reino");

        btn_encadenar.setText("Encadenar");
        btn_encadenar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_encadenarActionPerformed(evt);
            }
        });

        btn_siguiente.setText("Siguiente");
        btn_siguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_siguienteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addComponent(btn_encadenar))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbx_eucariotas)
                            .addComponent(cbx_procariotas)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(cbx_unicelular)
                                .addComponent(cbx_multicelular)
                                .addComponent(cbx_heterotrofo)
                                .addComponent(cbx_autotrofo)
                                .addComponent(cbx_paredCelular, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(cbx_movillidad)))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(btn_siguiente)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(lbl_res, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(41, 41, 41))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbx_eucariotas)
                    .addComponent(jLabel1))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbx_procariotas)
                    .addComponent(lbl_res, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(cbx_unicelular)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbx_multicelular)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbx_autotrofo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbx_heterotrofo)
                        .addGap(28, 28, 28))
                    .addComponent(cbx_paredCelular, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cbx_movillidad)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_encadenar)
                    .addComponent(btn_siguiente))
                .addContainerGap(49, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbx_eucariotasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbx_eucariotasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbx_eucariotasActionPerformed

    private void cbx_procariotasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbx_procariotasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbx_procariotasActionPerformed

    private void cbx_unicelularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbx_unicelularActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbx_unicelularActionPerformed

    private void cbx_multicelularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbx_multicelularActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbx_multicelularActionPerformed

    private void cbx_autotrofoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbx_autotrofoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbx_autotrofoActionPerformed

    private void cbx_heterotrofoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbx_heterotrofoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbx_heterotrofoActionPerformed

    private void cbx_paredCelularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbx_paredCelularActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbx_paredCelularActionPerformed

    private void cbx_movillidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbx_movillidadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbx_movillidadActionPerformed

    private void btn_encadenarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_encadenarActionPerformed
        // TODO add your handling code here:
        String euc = "", proc = "", uni = "", multi = "",auto = "",hete = "",pared = "",movil = "";
        if (cbx_eucariotas.isSelected()) {
            euc = "si";
        } else {
            euc = "no";
        }
        if (cbx_procariotas.isSelected()) {
            proc = "si";
        } else {
            proc = "no";
        }
        if (cbx_unicelular.isSelected()) {
            uni = "si";
        } else {
            uni = "no";
        }
        if (cbx_multicelular.isSelected()) {
            multi = "si";
        } else {
            multi = "no";
        }
        if (cbx_autotrofo.isSelected()) {
            auto = "si";
        } else {
            auto = "no";
        }
        if (cbx_heterotrofo.isSelected()) {
            hete = "si";
        } else {
            hete = "no";
        }
        if (cbx_paredCelular.isSelected()) {
            pared = "si";
        } else {
            pared = "no";
        }
        if (cbx_movillidad.isSelected()) {
            movil = "si";
        } else {
            movil = "no";
        }
         System.out.println("\nEucariotas=" + euc + "\nProcariotas=" + proc + "\nUnicelular=" + uni + "\nMulticelular=" + multi+
                 "\nAutotrofo="+auto+"\nHeterotrofo="+hete+"\nPared celular="+pared+"\nMovilidad="+movil);
        c = objbr.getReino(euc, proc, uni, multi,auto,hete,pared,movil);
        System.out.println("Reino1=" + c);
        lbl_res.setText(c);
    }//GEN-LAST:event_btn_encadenarActionPerformed

    private void btn_siguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_siguienteActionPerformed
        // TODO add your handling code here:
        if (c == null) {
            JOptionPane.showMessageDialog(this,
                    "Verifica las entradas", "Error",
                    JOptionPane.ERROR_MESSAGE);
    }                                        
            if (c.equals("Animalia")) {
            this.dispose();
            Vfilo1 vfilo1 = new Vfilo1(c);
            vfilo1.setVisible(true);
        }
        
    }//GEN-LAST:event_btn_siguienteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Vreino.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Vreino.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Vreino.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Vreino.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Vreino().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_encadenar;
    private javax.swing.JButton btn_siguiente;
    private javax.swing.JCheckBox cbx_autotrofo;
    private javax.swing.JCheckBox cbx_eucariotas;
    private javax.swing.JCheckBox cbx_heterotrofo;
    private javax.swing.JCheckBox cbx_movillidad;
    private javax.swing.JCheckBox cbx_multicelular;
    private javax.swing.JCheckBox cbx_paredCelular;
    private javax.swing.JCheckBox cbx_procariotas;
    private javax.swing.JCheckBox cbx_unicelular;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lbl_res;
    // End of variables declaration//GEN-END:variables
}
